spring.application.name=cloud-support-automation-api
spring.profiles.active=dev

springdoc.cache.disabled=true
logging.level.org.cloud.automation.api.config=DEBUG

# These properties configure the custom thread pool for @Async tasks.
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=25
spring.task.execution.thread-name-prefix=AsyncTask-

