spring.datasource.url=jdbc:tc:postgresql:15-alpine:///cloud_support_automation                                                      \u2502
spring.datasource.username=test                                                                                                     \u2502
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
